name: build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      
    - name: Setup nuget
      uses: nuget/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0

    - name: Restore Packages
      run: nuget restore "EternalSoundMetadataPatcher.sln"

    - name: Build app
      run: msbuild "EternalSoundMetadataPatcher\EternalSoundMetadataPatcher.csproj" -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload app
      run: gh release upload ${{github.event.release.tag_name}} "EternalSoundMetadataPatcher/bin/Release/EternalSoundMetadataPatcher.exe" 
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
